name: cd

on:
  push:
    branches: [main]


jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
        
      - name: Build app
        run: ./scripts/buildprod.sh

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
         service_account_key: ${{ secrets.GCP_CREDENTIALS }}
         project_id: ${{ secrets.notely-410710 }}
      
      - name: Build and push Docker image
        run: |
          gcloud builds submit --tag REGION-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE:TAG .

